const availableTTsVoices = [
    { id: "sd-in-x-end-local", language: "sd-IN", name: "sd-in-x-end-local" },
    { id: "es-es-x-eea-local", language: "es-ES", name: "es-es-x-eea-local" },
    { id: "bn-in-x-bnm-local", language: "bn-IN", name: "bn-in-x-bnm-local" },
    { id: "bn-in-x-bnx-local", language: "bn-IN", name: "bn-in-x-bnx-local" },
    { id: "ta-in-x-tac-local", language: "ta-IN", name: "ta-in-x-tac-local" },
    { id: "da-dk-x-sfp-local", language: "da-DK", name: "da-dk-x-sfp-local" },
    { id: "gu-in-x-gum-local", language: "gu-IN", name: "gu-in-x-gum-local" },
    { id: "nl-be-x-bed-local", language: "nl-BE", name: "nl-be-x-bed-local" },
    { id: "lt-lt-x-amc-local", language: "lt-LT", name: "lt-lt-x-amc-local" },
    { id: "km-kh-x-khm-local", language: "km-KH", name: "km-kh-x-khm-local" },
    { id: "id-id-x-idc-local", language: "in-ID", name: "id-id-x-idc-local" },
    { id: "nl-nl-x-bmh-local", language: "nl-NL", name: "nl-nl-x-bmh-local" },
    { id: "nb-no-x-cmj-local", language: "nb-NO", name: "nb-no-x-cmj-local" },
    { id: "ko-kr-x-kob-local", language: "ko-KR", name: "ko-kr-x-kob-local" },
    { id: "fr-fr-x-vlf-local", language: "fr-FR", name: "fr-fr-x-vlf-local" },
    { id: "en-us-x-iog-local", language: "en-US", name: "en-us-x-iog-local" },
    { id: "cmn-tw-x-ctd-local", language: "zh-TW", name: "cmn-tw-x-ctd-local" },
    { id: "bg-bg-language", language: "bg-BG", name: "bg-bg-language" },
    { id: "pl-pl-x-bmg-local", language: "pl-PL", name: "pl-pl-x-bmg-local" },
    { id: "cy-GB-language", language: "cy-GB", name: "cy-GB-language" },
    { id: "en-in-x-ena-local", language: "en-IN", name: "en-in-x-ena-local" },
    { id: "cs-CZ-language", language: "cs-CZ", name: "cs-CZ-language" },
    { id: "fr-fr-x-frd-local", language: "fr-FR", name: "fr-fr-x-frd-local" },
    { id: "pa-in-x-pad-local", language: "pa-IN", name: "pa-in-x-pad-local" },
    { id: "jv-ID-language", language: "jv-ID", name: "jv-ID-language" },
    { id: "de-de-x-dea-local", language: "de-DE", name: "de-de-x-dea-local" },
    { id: "kok-IN-language", language: "kok-IN", name: "kok-IN-language" },
    { id: "nl-NL-language", language: "nl-NL", name: "nl-NL-language" },
    { id: "ja-jp-x-jab-local", language: "ja-JP", name: "ja-jp-x-jab-local" },
    { id: "en-us-x-tpc-local", language: "en-US", name: "en-us-x-tpc-local" },
    { id: "ro-ro-x-vfv-local", language: "ro-RO", name: "ro-ro-x-vfv-local" },
    { id: "pt-br-x-ptd-local", language: "pt-BR", name: "pt-br-x-ptd-local" },
    { id: "sw-ke-language", language: "sw-KE", name: "sw-ke-language" },
    { id: "sl-SI-language", language: "sl-SI", name: "sl-SI-language" },
    { id: "ms-my-x-mse-local", language: "ms-MY", name: "ms-my-x-mse-local" },
    { id: "es-US-language", language: "es-US", name: "es-US-language" },
    { id: "sv-SE-language", language: "sv-SE", name: "sv-SE-language" },
    { id: "pt-pt-x-jfb-local", language: "pt-PT", name: "pt-pt-x-jfb-local" },
    { id: "cmn-cn-x-cce-local", language: "zh-CN", name: "cmn-cn-x-cce-local" },
    { id: "as-IN-language", language: "as-IN", name: "as-IN-language" },
    { id: "nl-nl-x-dma-local", language: "nl-NL", name: "nl-nl-x-dma-local" },
    { id: "en-us-x-iol-local", language: "en-US", name: "en-us-x-iol-local" },
  ];
  
  